apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata-claim
  labels:
    app: ontologymanager-elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontologymanager-elasticsearch 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontologymanager-elasticsearch
  template:
    metadata:
      labels:
        app: ontologymanager-elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        fsGroup: 1000 
      containers:
      - name: ontologymanager-elasticsearch
        image: scibite/oio:6.8.1-clean
        ports:
          - containerPort: 9300
        env:
          - name: cluster.name
            value: elasticsearch
          - name: discovery.type
            value: single-node
          - name: xpack.security.enabled
            value: "false" 
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 1512Mi
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data/
          name: esdata
      volumes:
      - name: esdata
        persistentVolumeClaim:
          claimName: esdata-claim
--- 
apiVersion: v1
kind: Service
metadata:
  name: ontologymanager-elasticsearch
  labels:
    app: ontologymanager-elasticsearch
spec:
  ports:
  - port: 9300
  selector:
    app: ontologymanager-elasticsearch
